### ISSUE TITLE
Struggling to run the pipeline-nanopore-ref-isoforms

### ISSUE THREAD

**Issue by adelfma3** [nanoporetech/pipeline-nanopore-ref-isoforms#11]
Hi, 
I have tried to used this pipelines "pipeline-nanopore-ref-isoforms " to find the full length transcript.  It seems pretty clear. I cloned the pipeline and the pipeline toolset and created a new Conda environment based on the env.yaml. Then, I run "snakemake --use-conda -j 4"

Unfortunately, nothing has been done. I also cannot find the snakemake.log (2020-10-27T123302.919841.snakemake.log) because it was not in the indicated folder.

(stringtie) afma3@DT-2R1119-102:~/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms$ snakemake --use-conda -j 4
Building DAG of jobs...
Nothing to be done.
Complete log: /home/afma3/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms/.snakemake/log/2020-10-27T123302.919841.snakemake.log

Thanks in advance,
afma3

**Comment by philres** [comment]
Hi and thanks for your message,

Could you please copy and paste your config file (config.yml) here?

Thanks,
Philipp

**Comment by adelfma3** [comment]
Thanks, Philipp, for the quick respond, you give me a hope that will be solved

This is the config.ymal I used,

---
## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-nanopore-ref-isoforms"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "evaluation"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms.git"

## Pipeline-specific parameters:

# Input genome
genome_fasta: "evaluation/data/Homo_sapiens.GRCh38.dna.chromosome.10.fa"

existing_annotation: "evaluation/data/Homo_sapiens.GRCh38.95.chromosome.10.gff3"

# cDNA or direct RNA reads in fastq format
reads_fastq: "evaluation/data"

# The path above is a directory, find and concatenate fastq files:
concatenate: true

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: true

# Options passed to pychopper:
pychopper_opts: ""

# Extra option passed to minimap2 when generating index
minimap_index_opts: "-k14"

# Extra options passed to minimap2
minimap2_opts: "-uf "
# Add this for SIRV data:
# "--splice-flank=no"

# Minmum mapping quality
minimum_mapping_quality: 40

# Internal priming filter context size:
poly_context: 24

# Number of alignments to sample for context plots:
context_plt_alns: 5000

# Maximum allowed poly(A) length in the genome near the 3' end of mapping:
max_poly_run: 8

# Minimium number of reads in BAM bundles:
bundle_min_reads: 50000

# Use exiting annotation as guide for stringtie:
use_guide_annotation: true

# Options passed to stringtie:
stringtie_opts: " --conservative "

# Options passed to gffcompare:
gffcompare_opts: " -R "

# Threads:
threads: 4



________________________________

**Comment by philres** [comment]
Ok looking at this you have moved your reference genome here:
`evaluation/data/Homo_sapiens.GRCh38.dna.chromosome.10.fa`
Your annotation to here:
`"evaluation/data/Homo_sapiens.GRCh38.95.chromosome.10.gff3`
and your reads here:
`evaluation/data`

Is this correct? If so, could you please change those relative paths to absolute paths and make sure that the are all correct? This should not be necessary but just to be 100% sure everything is where it is supposed to be.

In addition could you please change the
`workdir_top: "evaluation"`
to 
`workdir_top: "output"`

and try to run the pipeline again?

When you run the pipeline could you please use:
`snakemake --use-conda -j 4 -pr`

and post the full output here?

Thanks,
Philipp

**Comment by adelfma3** [comment]
Hi Philipp,

I changed the reference, annotation & data path to be in absolute path in config.yaml. I also changed the workdir_top from "evaluation" to "output" in config.ymal and changed the name of the folder to "output". Then run "snakemake --use-conda -j 4 -pr"

I used my data as well as the accompanying and both give this


(stringtie) afma3@DT-2R1119-102:~/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output$ pwd
/home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output
(stringtie) afma3@DT-2R1119-102:~/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output$ cd ..
(stringtie) afma3@DT-2R1119-102:~/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms$ snakemake --use-conda -j 4 -pr
Building DAG of jobs...
Creating conda environment /home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/env.yml...
Downloading and installing remote packages.
Environment for ../../env.yml created (location: .snakemake/conda/d2482105)
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
count jobs
1 dump_versions
1

[Thu Oct 29 17:46:49 2020]
rule dump_versions:
    output: versions.txt
    jobid: 0
    reason: Missing output files: versions.txt


    command -v conda > /dev/null && conda list > versions.txt

Activating conda environment: /home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output/pipeline-nanopore-ref-isoforms/.snakemake/conda/d2482105
[Thu Oct 29 17:46:53 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/.snakemake/log/2020-10-29T174553.127953.snakemake.log



And this the modified config.ymal:

## General pipeline parameters:

# Name of the pipeline:
pipeline: "pipeline-nanopore-ref-isoforms"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "output"
# Repository URL:
repo: "https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms.git"

## Pipeline-specific parameters:

# Input genome
genome_fasta: "/home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output/data/SIRV_150601a.fasta"

existing_annotation: "/home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output/data/SIRV_isofroms.gtf"

# cDNA or direct RNA reads in fastq format
reads_fastq: "/home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output/data"

# The path above is a directory, find and concatenate fastq files:
concatenate: true

# Process cDNA reads using pychopper, turn off for direct RNA:
run_pychopper: true

# Options passed to pychopper:
pychopper_opts: ""

# Extra option passed to minimap2 when generating index
minimap_index_opts: "-k14"

# Extra options passed to minimap2
minimap2_opts: "-uf "
# Add this for SIRV data:
# "--splice-flank=no"

# Minmum mapping quality
minimum_mapping_quality: 40

# Internal priming filter context size:
poly_context: 24

# Number of alignments to sample for context plots:
context_plt_alns: 5000

# Maximum allowed poly(A) length in the genome near the 3' end of mapping:
max_poly_run: 8

# Minimium number of reads in BAM bundles:
bundle_min_reads: 50000

# Use exiting annotation as guide for stringtie:
use_guide_annotation: true

# Options passed to stringtie:
stringtie_opts: " --conservative "

# Options passed to gffcompare:
gffcompare_opts: " -R "

# Threads:
threads: 4

 Thanks

Adel

________________________________

**Comment by adelfma3** [comment]
By the way I'm using conda environment to run the pipeline. When I checked how many environments do I have. I've found 6 unnamed virtual environments were created that I'm sure not created by me. And all of them have the log file that was indicated in the error. I thought it might be relate to the error and worth noting to mention it.

(base) afma3@DT-2R1119-102:~/Documents/H292_cDNA/stringtie_1$ conda info --envs
# conda environments:
#
                         /home/afma3/Documents/H292_cDNA/pipeline-nanopore-ref-isoforms/evaluation/pipeline-evaluation-dmel/.snakemake/conda/af0e4f61
                         /home/afma3/Documents/H292_cDNA/pipeline-nanopore-ref-isoforms/evaluation/pipeline-nanopore-ref-isoforms/.snakemake/conda/c1f3cb0b
                         /home/afma3/Documents/H292_cDNA/stringtie/pipeline-nanopore-ref-isoforms/evaluation/pipeline-nanopore-ref-isoforms/.snakemake/conda/f84fb4e1
                         /home/afma3/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms/output/pipeline-nanopore-ref-isoforms/.snakemake/conda/db5279fa
                         /home/afma3/Documents/H292_cDNA/stringtie_test/pipeline-nanopore-ref-isoforms/output/pipeline-nanopore-ref-isoforms/.snakemake/conda/d2482105
base                  *  /home/afma3/miniconda3
Pinfish                  /home/afma3/miniconda3/envs/Pinfish
py36                     /home/afma3/miniconda3/envs/py36
snakemake                /home/afma3/miniconda3/envs/snakemake
stringtie                /home/afma3/miniconda3/envs/stringtie
                         /home/afma3/miniconda3/envs/stringtie/envs/stringtie

Thanks

adel
________________________________

**Comment by philres** [comment]
Hi again,

Could you please make sure the the output directory is removed and then rerun? 

Meaning find your output directory and run:
```
rm -rf output
```
and then run the pipeline again?

Thanks,
Philipp

**Comment by adelfma3** [comment]
Hi Philipp,

My apology to respond late. I don't understand why should I have to delete the output directory (was previously evaluation) that contains my reads and reference files. However, I did and I run the command and delete the output folder as you recommend.  This is what I got:

Building DAG of jobs...
Creating conda environment /home/afma3/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms/env.yml...
Downloading and installing remote packages.
Environment for ../../env.yml created (location: .snakemake/conda/db5279fa)
Using shell: /bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	dump_versions
	1

[Thu Nov  5 18:19:01 2020]
rule dump_versions:
    output: versions.txt
    jobid: 0
    reason: Missing output files: versions.txt


    command -v conda > /dev/null && conda list > versions.txt
    
Activating conda environment: /home/afma3/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms/output/pipeline-nanopore-ref-isoforms/.snakemake/conda/db5279fa
[Thu Nov  5 18:19:05 2020]
Finished job 0.
1 of 1 steps (100%) done
Complete log: /home/afma3/Documents/H292_cDNA/stringtie_1/pipeline-nanopore-ref-isoforms/.snakemake/log/2020-11-05T181707.037399.snakemake.log

**Comment by peterkilfeather** [comment]
Also having exactly the same issue.

**Comment by bsipos** [comment]
Indeed not specifying the "all" target seems to be the issue. Please specify it in the command line as described in the README.
