### ISSUE TITLE
Syntax error in Snakefile with SIRV data

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pipeline-nanopore-ref-isoforms#13]
Hi I am trying to just run the pipeline on the SIRV sample data but it is throwing an error. I suspect it may be related to my version of snakemake 3.13.3

```
❯ snakemake --use-conda -j 12 all
SyntaxError in line 144 of /home/callum/pipeline-nanopore-ref-isoforms/Snakefile:
invalid syntax
```

**Comment by bsipos** [comment]
Yes, probably that snakemake version does not support the "checkpoint" feature used in this pipeline. Could you please upgrade snakemake and try again?

**Comment by callumparr** [comment]
Indeed this was the case. I had some issues upgrading the snakemake through conda. So I ended up create an env to install up to date snakemake. This runs perfectly on SIRV and dmel now. Thank you.
