### ISSUE TITLE
Unstranded Protocol 

### ISSUE THREAD

**Issue by RogerioRibeiro201505534** [nanoporetech/pipeline-nanopore-ref-isoforms#8]
Hi there!
I have a set of 12 ONT samples, which have been basecalled using Guppy 4.0 (model accurate). This process was not performed by me, and I´m unsure of some details, what I do know is that 1) probably won´t be able to perform the basecall again due to time constraints 2) The adaptors/primers were removed (I already testes pychopper in one sample and could only recover orientation if 14% of the reads. 

I took a look at the Snakefile and it seems that some step requires a strand-specific library, particularly the stringtie (-rf option) and the Seqkit "AlnContext (stranded = True). 

Is my data compatible with your pipeline? What steps should I skip/modify If I want to use my data?

**Comment by bsipos** [comment]
Hello!

Indeed with the primers trimmed pychopper cannot determine the read orientations. Since having stranded reads provides many advantages my advice is to re-basecall the data withouth trimming.
